### ISSUE TITLE
Pac

### ISSUE THREAD

**Issue by ghost** [octavore/lightproxy#2]
I have seen this before but don't understand the concept. I think clodflare are using it for tunnelling.

If you get a chance could you add some links about it to the reader.

The project looks really good.
Have you tested it on windows ?

**Comment by octavore** [comment]
sorry for the delay in getting back to you! I've just added some links to the readme, as well as some [instructions for configuring a PAC file in windows](https://pypac.readthedocs.io/en/latest/about_pac.html#windows). I have not tested it though, but if you manage to get it running, do let me know :)
